version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/postgres:12.3
        environment:
          # 1
          BUNDLER_VERSION: 2.3.26
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_cd_test
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.3.26
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y nodejs postgresql-client libpq-dev
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
#      - run:
#          name: Run RuboCop
#          command: |
#            bundle exec rubocop
      - run:
          name: Create and migrate database
          command: |
            bundle exec rails db:create RAILS_ENV=test
            bundle exec rails db:migrate RAILS_ENV=test
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec