version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y nodejs postgresql-client libpq-dev
            gem install bundler -v 2.3.26
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
#      - run:
#          name: Run RuboCop
#          command: |
#            bundle exec rubocop
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec