name: Rspec
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
        bundler-cache: true
    - name: Install dependencies
      run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
    - name: Install Postgres Client
      run: sudo apt-get install libpq-dev
    - name: Create and migrate database
      run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
    - name: Run Rspec
      run: bundle exec rspec

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
          bundler-cache: true # caches installed gems
      - name: Install Dependencies
        run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
      - name: test bash
        run: echo $SSH_PRIVATE_KEY
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up SSH
        uses: ssh-actions/ssh-agent@v1.0.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy with Capistrano
        run: bundle exec cap production deploy