name: Rspec
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.1
    - name: Install dependencies
      run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
    - name: Run Rspec
      run: bundle exec rspec

